version: '3.7'

services:
  frontend:
    restart: unless-stopped
    image: leonaistrefi/frontend-groups:latest
    container_name: leona-frontend
    depends_on:
      - backend
    ports:
      - 3000:80
  backend:
    restart: unless-stopped
    image: leonaistrefi/backend-groups:latest
    container_name: leona-backend
    ports:
      - 8080:8080
    environment:
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: Leona-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
